version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
    commit-message:
      prefix: "deps"
    groups:
      kotlin:
        patterns:
          - "org.jetbrains.kotlin*"
      pitest:
        patterns:
          - "org.pitest*"
      testing:
        patterns:
          - "io.kotest*"
          - "org.junit*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "ci"
    commit-message:
      prefix: "ci"
