package io.github.ioplane.mutaktor.pitest

import org.pitest.mutationtest.build.InterceptorParameters
import org.pitest.mutationtest.build.InterceptorType
import org.pitest.mutationtest.build.MutationInterceptor
import org.pitest.mutationtest.build.MutationInterceptorFactory
import org.pitest.mutationtest.engine.Mutater
import org.pitest.mutationtest.engine.MutationDetails
import org.pitest.plugin.Feature

/**
 * PIT [MutationInterceptorFactory] that registers the [KotlinJunkFilter].
 *
 * Discovered via `META-INF/services/org.pitest.mutationtest.build.MutationInterceptorFactory`.
 */
class KotlinJunkFilterFactory : MutationInterceptorFactory {

    override fun createInterceptor(params: InterceptorParameters): MutationInterceptor =
        KotlinJunkFilter()

    override fun provides(): Feature =
        Feature.named("KOTLIN_JUNK")
            .withOnByDefault(true)
            .withDescription(description())

    override fun description(): String =
        "Filters junk mutations in Kotlin compiler-generated bytecode"
}

/**
 * A unified [MutationInterceptor] that removes nonsensical mutations produced
 * by the Kotlin compiler in generated bytecode.
 *
 * Filtered patterns:
 * 1. Kotlin null-check intrinsics (`Intrinsics.check*`)
 * 2. Data-class generated methods (`copy`, `componentN`, `toString`, `hashCode`, `equals`)
 * 3. Coroutine state-machine dispatch (`invokeSuspend` in `$…` continuation classes)
 * 4. Default-implementation bridge classes (`$DefaultImpls`)
 * 5. `when`-expression hashcode dispatch (heuristic: method named `<clinit>` or
 *    description mentioning `hashCode`)
 */
class KotlinJunkFilter : MutationInterceptor {

    /** Regex matching data-class generated method names. */
    private val dataClassMethodPattern: Regex =
        Regex("""^(copy|copy\${'$'}default|component\d+|toString|hashCode|equals)$""")

    override fun type(): InterceptorType = InterceptorType.FILTER

    override fun begin(clazz: org.pitest.bytecode.analysis.ClassTree) {
        // No per-class state needed — all decisions are based on MutationDetails.
    }

    override fun intercept(
        mutations: Collection<MutationDetails>,
        mutater: Mutater,
    ): Collection<MutationDetails> =
        mutations.filterNot { isKotlinJunk(it) }

    override fun end() {
        // nothing to clean up
    }

    // -----------------------------------------------------------------
    // Filter predicates
    // -----------------------------------------------------------------

    private fun isKotlinJunk(mutation: MutationDetails): Boolean =
        isDefaultImplsClass(mutation) ||
            isIntrinsicsNullCheck(mutation) ||
            isDataClassGeneratedMethod(mutation) ||
            isCoroutineStateMachine(mutation) ||
            isWhenHashcodeDispatch(mutation)

    /**
     * Pattern 4 — `$DefaultImpls` bridge classes generated for Kotlin interfaces
     * with default method bodies.
     */
    private fun isDefaultImplsClass(mutation: MutationDetails): Boolean {
        val className = mutation.className.asJavaName()
        return className.endsWith("\$DefaultImpls")
    }

    /**
     * Pattern 1 — mutations inside Kotlin null-check intrinsic calls.
     *
     * The mutation description typically references `kotlin/jvm/internal/Intrinsics`.
     */
    private fun isIntrinsicsNullCheck(mutation: MutationDetails): Boolean {
        val desc = mutation.description
        return desc.contains("Intrinsics") ||
            desc.contains("checkNotNull") ||
            desc.contains("checkParameterIsNotNull") ||
            desc.contains("checkNotNullParameter") ||
            desc.contains("checkNotNullExpressionValue")
    }

    /**
     * Pattern 2 — data-class generated methods: `copy`, `copy$default`,
     * `component1`..`componentN`, `toString`, `hashCode`, `equals`.
     */
    private fun isDataClassGeneratedMethod(mutation: MutationDetails): Boolean =
        dataClassMethodPattern.matches(mutation.method)

    /**
     * Pattern 3 — coroutine state-machine dispatch.
     *
     * Heuristic: mutations in a method named `invokeSuspend` inside a class
     * whose name suggests it is a compiler-generated continuation
     * (contains `$` — typical for inner/anonymous classes).
     */
    private fun isCoroutineStateMachine(mutation: MutationDetails): Boolean {
        if (mutation.method != "invokeSuspend") return false
        val className = mutation.className.asJavaName()
        return className.contains("$")
    }

    /**
     * Pattern 5 — `when`-expression hashcode dispatch.
     *
     * Heuristic: the mutation description mentions both `hashCode` in a
     * switch-like context. Kotlin compiles `when(string)` to
     * `hashCode()`+`equals()` chains where mutating the equality check is
     * usually unkillable.
     */
    private fun isWhenHashcodeDispatch(mutation: MutationDetails): Boolean {
        val desc = mutation.description
        return desc.contains("hashCode") && desc.contains("equals")
    }
}
